### ISSUE TITLE
Message board and...

### ISSUE THREAD

**Issue by LordBBC** [mm201/pkmn-classic-framework#23]
Hello, I have become a frequent user of this server. I have a few ideas that could improve the experience and I would like to share with you. First of all, the addition of a message board in a new tab, it could be with or without signing in. In order to arrange trades in a server not very populated... I would also like that the impossible trades were removed, something like a countdown to retrieve the pkm or it will be deleted. Hope you take into account these suggestions I make. Good work and way to go.

**Comment by PokeAcer549** [comment]
Impossible trades being stopped is to be added, and one couldn't remove the Pokémon because the game would still return it
On 26 Jan 2016 11:48, LordBBC <notifications@github.com> wrote:Hello, I have become a frequent user of this server I have a few ideas that could improve the experience and I would like to share with you First of all, the addition of a message board in a new tab, it could be with or without signing in In order to arrange trades in a server not very populated I would also like that the impossible trades were removed, something like a countdown to retrieve the pkm or it will be deleted Hope you take into account these suggestions I make Good work and way to go

**Comment by mm201** [comment]
I plan to block impossible requests from being made (https://github.com/mm201/pkmn-classic-framework/issues/4) but it's part of a larger anti-cheat database which tracks the release status of things. (i.e. Celebi lv. 9 and under is only illegal because there was never a Celebi given away at that low a level.)

I would like to add some form of communication, but a simplistic one like a shoutbox. I don't want to have to deal with the effort involved in moderating a forum.

A login system is on the way so I can provide Game Sync and stat checking.

**Comment by PokeAcer549** [comment]
GameSync?! :D

**Comment by LordBBC** [comment]
A shoutbox would be useful. An anti-cheat database is needed. I requested a Dewott, I got a lv.10 Dewott that crashed the game everytime I tried to see the details... However I use to send past events to my game and I think that doesn't spoil the game. Thank you for answering so fast.

**Comment by PokeAcer549** [comment]
Mini update: RiiConnect24 devs are working on WC24 mail (ty @shutterbug2000 for helping c:) - did we ever get dumps of the "register your Wii and get GTS notifications!" process? We could probably put something in the backend for the service

**Comment by mm201** [comment]
I don't have a Wii.

How did that ever work, anyway? I need a way to link a savefile to a user account but there's no easy way I know of on GenIV. (just hacks like Pokecheck did)

**Comment by PokeAcer549** [comment]
PID. It's how Ninty did it :stuck_out_tongue:

**Comment by PokeAcer549** [comment]
IIRC it'd send a message to the gs server saying "My Wii FC is 1234-5678-9012-3456, and my PID is 123456." then gamestats would know and Nintendo added some code so when traded it sends an email for that PID (w1234567890123456@wii.com) saying of such. Ofc we'd probably just have a small thing you can GET or POST to :stuck_out_tongue:

**Comment by mm201** [comment]
Wouldn't that be the PID of the Wii, not the DS game? Also, is it real PID or GTS PID?

And I guess a Wii is required for this whole process anyway.

**Comment by PokeAcer549** [comment]
Your DS PID, and most likely the GTS one (which is the PID of the first Pokemon connection to GTS from that 3DS)
And yes, but we could also have email updates aswell :3

**Comment by m0n00n3** [comment]
Anyone battling?

**Comment by PokeAcer549** [comment]
^ not needed, doesnt help, this is an issue not a forum

@mm201 a WC24 Mail PoC is being worked on by RiiConnect24; would we be able to contact you regarding it?

**Comment by PokeAcer549** [comment]
Huge Update: RiiConnect24 has Mail working @mm201; we could add in something that sends mail from the old Pokemon News mail (we'd talk to you regarding this), as that could be quite helpful to some.

**Comment by mm201** [comment]
I can throw together a json API real quick if I know what values you need.

**Comment by PokeAcer549** [comment]
Perhaps we should close this, so that people don't comment here for it?

**Comment by mm201** [comment]
Resolving this since we do now have a [Discord group](https://discord.com/invite/sDQVKFxvMM). While there is more to come, keeping this generic issue open doesn't help any.
