### ISSUE TITLE
R&D into WC24 GameStats

### ISSUE THREAD

**Issue by PokeAcer549** [mm201/pkmn-classic-framework#24]
Would a look at how Pokemon connected to Gamestats and registered a Wii be feasible. I know the WC24 mail aspect is gone (Hopefully it may come back thanks to us at RC24), however a regular email stating "Your pokemon x was taken by y. You received pokemon z with level y and gender a". I'd be willing to help with the mail hosting - I have a VPS that isn't blacklisted :stuck_out_tongue: 

--PokeAcer

**Comment by mm201** [comment]
I was thinking of doing SMS and/or web push notifications for that. It ties into the login system.

I don't know why I'd want to use WC24. There's too much research involved and it's only of benefit to players who have Wiis. Emulating WC24 is a noble cause but just not a good fit for this project.

If I had to guess, I'd say the magic happened on the WC24 server since it was under Nintendo's control, unlike gamestats. It could poll `result.asp` and report back once a pokemon is waiting there.

**Comment by PokeAcer549** [comment]
I see. Again, I know of some great APIs for SMS texting,along with email, so talk to me on Skype :stuck_out_tongue:

**Comment by mm201** [comment]
I'll keep you in mind when I get that far. 😝

**Comment by PokeAcer549** [comment]
Another way to do it wouldbe building an app that would check every so often for your own Pokemon, and when it says "Traded!" it'll email you. I'd love to try that out, would you mind if I did some tests?
The IPs I use are:
```
185.82.21.64
185.82.22.28
185.82.22.43
```
(IDK which it'll pick because it's 3 on the same VPS)

--PokeAcer

**Comment by mm201** [comment]
If you want to do that, I won't stop you, but be prepared for it to become obsolete when I make a serverside version.

**Comment by PokeAcer549** [comment]
I'll be happy to share my work with you, it's fine :P
Do you have anything on result.asp? :)
