### ISSUE TITLE
WI-FI Club

### ISSUE THREAD

**Issue by KingArokh** [mm201/pkmn-classic-framework#49]
Hi there

My brother and I got an issue by connecting each other via the WI-FI club in the Pokemon Center. (Pokemon Platinum) We both use DesMume 0.9.9 and we are connected successfully with the atlwfc server. (GTS for example works perfectly)

I tried the WI-FI club alone before with 2 emulators on the same network which gave me a 8xxxx error. I assumed the emulators disconnected each other (connection timeout) because they wanted to connect through the same network simultaneoulsy.

However, it is really strange when we tried to connect with 2 different networks. I don't get an error code at all. I clicked on the other player and tried to start a trade and he did accept. It kinda just does not connect us but it does not disconnect anyone of us either. The trade attempt simply cancels and the emulator continues to work normally.

We browsed through the altwfc issue section and the only possible solution we found so far is that there could be something wrong with the emulator. What are your experiences? Does WI-FI club even work with 2 emulators on Gen4? Is it really emulator related or is there another solution?

Thank you very much for your hard work!

**Comment by mm201** [comment]
Last I checked, Desmume does have compatibility problems with it. Real systems have worked for me, but emulators or a mix of the two will time out after trying to contact each other in the lobby, as you described. I'm fairly confident the problem lies with Desmume.

Also, since the Wi-Fi Club is totally AltWFC-side and doesn't actually touch the PCN server, I'm going to go ahead and close this. Good luck!
