### ISSUE TITLE
Just info on the 'not inplemented'.....

### ISSUE THREAD

**Issue by vigneshd332** [mm201/pkmn-classic-framework#51]
Are the not implemented features like game sync , wifi plaza and other things being worked on or are they totally abandoned? Is this project still actively developed?

**Comment by mm201** [comment]
I still have interest in the project, but it's certainly not going to be developing at the same frantic pace it had when the WFC originally went down. That's just reality. There's no looming deadline for me to race. I would gladly accept contributions of a decent quality and any research you may have. Otherwise, just be patient.

**Comment by vigneshd332** [comment]
I can help software wise. Like giving roms or firmware files or bios files and other shit. Just ask.
