### ISSUE TITLE
Support for IV generation Pokemon beyond 493 (ROM Hacking)

### ISSUE THREAD

**Issue by mikelan98** [mm201/pkmn-classic-framework#55]
I'm currently making a hack ROM based on Pokemon HG which will include all the 807 Pokémon, and I'm very interested in giving it an online support (GTS and Mystery Gift). May I contact with you for talking about the possibilities to collaborate and giving Pkmn Classic Network a support for my game? Thanks in advance ^_^

**Comment by mm201** [comment]
Your best bet would be to hack the URL strings to `gamestats.gs.nintendowifi.net` in the ROM to point to a custom domain name and host a PCN instance there. I don't want to risk regular players being traded nonsense their games can't understand.

The server itself will probably work fine, but the website may have broken images past Gen5 and possibly more display issues/crashes past Gen6 because of missing data. (It also seems my data importer isn't compatible with the latest veekun data which is something I should be working on.)

I'd be glad to discuss any bugs you may uncover in the process. Since this isn't an _ongoing issue_, I'll close this.
