### ISSUE TITLE
Correct display of HG/SS Apricorn Pokéballs

### ISSUE THREAD

**Issue by mm201** [mm201/pkmn-classic-framework#59]
RIght now they show as red Pokéballs because I don't have their ID numbers handy. (These numbers are NOT the same as regular items!)

**Comment by MightyJoeYoung** [comment]
I think I've got a handy list for you of their ID numbers as they are found in the PKMN structure

`

Ball Type | 0x83 | 0x86
-- | -- | --
master | 01 | 01
ultra | 02 | 02
great | 03 | 03
poké | 04 | 04
fast | 04 | 11
level | 04 | 12
lure | 04 | 13
heavy | 04 | 14
love | 04 | 15
friend | 04 | 16
moon | 04 | 17
sport | 04 | 18
safari | 05 | 05
net | 06 | 06
dive | 07 | 07
nest | 08 | 08
repeat | 09 | 09
timer | 0A | 0A
luxury | 0B | 0B
premier | 0C | 0C
dusk | 0D | 0D
heal | 0E | 0E
quick | 0F | 0F
cherish | 10 | 10

`

**Comment by Rempa212** [comment]
Hey, i know this is'nt the right place to ask for that, but i don't know where to do it soo..
So, i thought i could try to fix this issue and tried to setup a altwfc and a pkmnfoundation server to work with.
My altwfc server works, and i came up to the last step of the explaination of "Creating a pkmnFoundations server" (i only didn't set the DNS)
So everything seems to work (the mysql database has been filled by VeekunImport, and GlobalTerminalservice.exe runs. The "GTS" project has been published and the files have been placed to C:\inetpub\wwwroot ; IIS is enabled and ASP.NET for it too.
So, my question is : what is supposed to be shown when using my web browser and going to localhost ? Back when trying to setup everything, i had a mysql error page, but i fixed it by changing "pkmncf_pokedex_pokemon_Forms" to "pkmncf_pokedex_pokemon_forms" in DataMysql.cs line 3118 (so i guess it means at least something related to pkmnclassic is running when i'm going on this page), and now i only get the default IIS webpage. Is this normal ? What should i do to get the webpage that can be seen on http://pkmnclassic.net/ ? 
I'm sorry because i'm really a newbie with IIS and any king of C# web development, but i hope you can explain me what i'm doing wrong, so i can help you in this project.
Thanks :)

**Comment by mm201** [comment]
What about Park and Dream ball? Are they 0x19 and 0x1a?

**Comment by mm201** [comment]
It appears Park Ball isn't included and Dream Ball is 0x19. https://github.com/kwsch/PKHeX/blob/master/PKHeX.Core/Game/Enums/Ball.cs

All Pokéball types should be supported now so I can close this.
