### ISSUE TITLE
Planned events

### ISSUE THREAD

**Issue by thewolfpack23x** [mm201/pkmn-classic-framework#64]
Just to note, this was all made under the assumption that the events are controlled by this server. While it's great that we now have access to all the event pokemon distributed over the WFC, I was wondering if it would be possible to change it from constantly giving out random events to having specific events at specific times. To iterate on that, I'd prefer if these events weren't always available (maybe you could set the dates and times for each mystery gift on a calendar system which the service could read from) and if you could make it relate to something going on (such as having Jirachi for the anniversary of Gold and Silver or releasing Darkrai around Halloween). You could possibly also put notices on the website for upcoming events.

**Comment by InternalLoss** [comment]
This server does not control Mystery Gifts for either AltWFC or Wiimmfi.

**Comment by mm201** [comment]
Maybe in the far distant future implementing my own dls1 server would be interesting but that's a long time from now. And I did come up with a schedule way back in 2014: https://docs.google.com/spreadsheets/d/18ADsjRDMbDLPdhf-4iggcOTCiuS4_DcmCmec8NlddjQ/edit?usp=sharing

But since the altwfc server works well enough and there are a million more pressing things, I'll go ahead and close this.

**Comment by mm201** [comment]
Notably, turns out we can't do multiple events at once so my old schedule will need some changes.
